#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-demo"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

# D1 Database 绑定
[[d1_databases]]
# 修改点：将 binding 改为与你脚本中一致的名称
binding = "cloudflare-demo-db" 
database_name = "cloudflare-demo-db"
database_id = "1c5802dd-3bd6-4804-9209-8bc4c26cc40b"

# AI 绑定
[ai]
binding = "AI"

# 已移除冗余的 [functions] 避免报错